# ================================================================
# application.properties  —  message-service
# ================================================================
spring.application.name=message-service
spring.profiles.active=dev

# ----- Eureka Client -----
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ----- MySQL -----
spring.datasource.url=${MSG_DB_URL:jdbc:mysql://localhost:3306/connecthub_message?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MSG_DB_USERNAME:root}
spring.datasource.password=${MSG_DB_PASSWORD:P_22@LovePUBG}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ----- Server -----
server.port=8083

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
